### ISSUE TITLE
The video is deleted before processing, when it is found in the database

### ISSUE THREAD

**Issue by jessicaori** [jpsandovaln/AT2024Progra2ConverterService#24]
When executing the POST method of the '/video-to-images' route, and after validating that a 'file' was received, the video to be processed is deleted if it had already been previously sent by the user.

**File to check:** api/endpoints.py
**Line:** 33
**Error executing:** 
![image](https://github.com/user-attachments/assets/802466d8-c535-4594-8f5d-73f94c19f566)

![image](https://github.com/user-attachments/assets/8625e858-c460-41c8-a50c-30eebf020971)

**Comment by RhemJos** [comment]
You can use the converter-service branch, there are new files and endpoints.py has been removed

**Comment by jessicaori** [comment]
Rhem, I've been checking what could have happened with the operation of the VideoToVideo converter since on Tuesday when we presented the demo it was working perfectly when I merged my feat/video-converter-validator branch after validation by the entire team in charge of the Converter service.

After the demo presentation class, some teammates uploaded changes to the route in api/endpoints.py, and it is from there that what is currently in the 'develope' branch no longer works.

I suggest that you check the `/video-to-video` route of the `feat/video-converter-validator` branch and make the comparison.

I am sharing with you the code and tests I carried out between the route that was up until Tuesday of the demo:

![image](https://github.com/user-attachments/assets/723c5906-d5b1-4510-be29-4291cba615e5)

![image](https://github.com/user-attachments/assets/dff5a56c-41b4-4113-84a2-c424df1de18a)

And the current code changed this week on 'develop':

![image](https://github.com/user-attachments/assets/2c543144-2c75-4916-a77f-6e7dd11dc5b8)

![image](https://github.com/user-attachments/assets/77f0a56d-090e-41ec-833e-fc9af178976f)

**Comment by jessicaori** [comment]
I also tested the code that was initially there, with the interface (just the `format` parameter for the moment) and it is indeed converting it ⭐ 

![image](https://github.com/user-attachments/assets/8b703fca-6b42-4ff8-bc4d-1cba3915be2a)

**Comment by jessicaori** [comment]
> I noticed that the main branch is outdated and unstable, particularly with the video-to-video conversion download is not working since the last sprint. The update depends on your review of the audio service PR from 3 days ago. Could you please review it when possible?

Something I'd like to mention is that the issue raised is about the VideoToImages endpoint. The bug you mention in Video-To-Video converter and the AudioConverter update do not directly affect that endpoint.

I'd also like to mention that I hadn't reviewed the AudioConverter PR until now, because this week I've been working entirely on the UI interface, my assigned task, but okay, I'll review it ⭐ 

![image](https://github.com/user-attachments/assets/88b3002b-0892-4650-bcb5-291dc6ab924a)

**Comment by RhemJos** [comment]
> > I noticed that the main branch is outdated and unstable, particularly with the video-to-video conversion download is not working since the last sprint. The update depends on your review of the audio service PR from 3 days ago. Could you please review it when possible?
> 
> Something I'd like to mention is that the issue raised is about the VideoToImages endpoint. The bug you mention in Video-To-Video converter and the AudioConverter update do not directly affect that endpoint.
> 
> I'd also like to mention that I hadn't reviewed the AudioConverter PR until now, because this week I've been working entirely on the UI interface, my assigned task, but okay, I'll review it ⭐
> 
> ![image](https://private-user-images.githubusercontent.com/66490864/386801985-88b3002b-0892-4650-bcb5-291dc6ab924a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MTc1NTcsIm5iZiI6MTczMTcxNzI1NywicGF0aCI6Ii82NjQ5MDg2NC8zODY4MDE5ODUtODhiMzAwMmItMDg5Mi00NjUwLWJjYjUtMjkxZGM2YWI5MjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDAwMzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYjg0MjE2ZTI1YmUzOTdkNGE1NDdiMGI1NTI2YTQ4ODA0NjJlMjI4NWYyMGRkNzVlMTdkODRiYmIyZWY2NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WlrI3X20yEo9gQ01YgNArG_0-1LAeyDbrycxRZS_gRk)

I'm sorry, I didn't explain myself well. I meant to say that develop branch is not working well with some functionalities, an **example** is the **video-to-video conversion download**. So I was just suggesting that for now you can consider the converter-service branch, which while not the main branch, is where bugs are currently being fixed and changes are being incorporated. 

I'm sorry for the misunderstanding.
